//created on: 05-Jun-2014
package SaboteurProxy

import agents.*;
import facts.*;



global org.apache.log4j.Logger logger



rule "Getting excluded is bad"
	when
		$agent : ProxyAgent($controller : owner, Active == false)
		eval($agent.IsAvatar())
	then
		logger.info("I got kicked out and this is bad.");
		$agent.decreasePreference(45);
end

rule "Depletion means ultimate victory"

	when 

        $lose : Lose ( $agent : causer )
        eval( $agent instanceof ProxyAgent )
        $proxy : ProxyAgent ( ) from $lose.getCauser()
        $avatar : ProxyAgent( )
        eval( $avatar.IsAvatar() )
    then
    	logger.info("Game over. Exactly what I hoped");
    	$avatar.setPreference(100);
    	$avatar.setPreferenceLocked(true);
    	
end
		